apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: threat-int
  name: {{ include "threat-dashboard.fullname" . }}-postgres-pvc
  labels:
    app: {{ include "threat-dashboard.name" . }}-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
